# Data Dictionary

## 0. Load Data

In [1]:
import pandas as pd
import numpy as np
# Load the dataset
df = pd.read_csv('data/raw/cardiovascular_risk_dataset.csv')

# Display the first few rows of the dataset
df.head()

,Patient_ID,age,bmi,systolic_bp,diastolic_bp,cholesterol_mg_dl,resting_heart_rate,smoking_status,daily_steps,stress_level,physical_activity_hours_per_week,sleep_hours,family_history_heart_disease,diet_quality_score,alcohol_units_per_week,heart_disease_risk_score,risk_category
0,1,62,25.0,142,93,247,72,Never,11565,3,5.6,8.2,No,7,0.7,28.1,Medium
1,2,54,29.7,158,101,254,74,Current,4036,8,0.5,6.7,No,5,4.5,63.0,High
2,3,46,36.2,170,113,276,80,Current,3043,9,0.4,4.0,No,1,20.8,73.1,High
3,4,48,30.4,153,98,230,73,Former,5604,5,0.6,8.0,No,4,8.5,39.5,Medium
4,5,46,25.3,139,87,206,69,Current,7464,1,2.0,6.1,No,5,3.6,29.3,Medium

## 1. Create Data Dictionary

In [2]:
# Create Data Dictionary Base
data_dictionary = pd.DataFrame({
    'Field Name': ["Patient_ID","age", "bmi", "systolic_bp", "diastolic_bp", "cholesterol_mg_dl",
                   "resting_heart_rate", "smoking_status", "daily_steps", "stress_level",
                   "physical_activity_hours_per_week", "sleep_hours", "family_history_heart_disease",
                   "diet_quality_score", "alcohol_units_per_week", "heart_disease_risk_score", "risk_category"],
})

data_dictionary

                          Field Name
0                         Patient_ID
1                                age
2                                bmi
3                        systolic_bp
4                       diastolic_bp
5                  cholesterol_mg_dl
6                 resting_heart_rate
7                     smoking_status
8                        daily_steps
9                       stress_level
10  physical_activity_hours_per_week
11                       sleep_hours
12      family_history_heart_disease
13                diet_quality_score
14            alcohol_units_per_week
15          heart_disease_risk_score
16                     risk_category

In [3]:
# Add Data Type
data_dictionary['Data Type'] = data_dictionary['Field Name'].apply(lambda x: str(df[x].dtype))

data_dictionary

                          Field Name Data Type
0                         Patient_ID     int64
1                                age     int64
2                                bmi   float64
3                        systolic_bp     int64
4                       diastolic_bp     int64
5                  cholesterol_mg_dl     int64
6                 resting_heart_rate     int64
7                     smoking_status    object
8                        daily_steps     int64
9                       stress_level     int64
10  physical_activity_hours_per_week   float64
11                       sleep_hours   float64
12      family_history_heart_disease    object
13                diet_quality_score     int64
14            alcohol_units_per_week   float64
15          heart_disease_risk_score   float64
16                     risk_category    object

In [4]:
# Add Description
descriptions = {
    "Patient_ID": "Unique identifier for each patient.",
    "age": "Age of the patient in years.",
    "bmi": "Body Mass Index, indicating body fat based on height and weight.",
    "systolic_bp": "Systolic blood pressure level.",
    "diastolic_bp": "Diastolic blood pressure level.",
    "cholesterol_mg_dl": "Total cholesterol level in mg/dL.",
    "resting_heart_rate": "Resting heart rate in beats per minute.",
    "smoking_status": "Smoking category (Never, Former, Current).",
    "daily_steps": "Average number of steps taken per day.",
    "stress_level": "Stress level on a scale from 1 to 10.",
    "physical_activity_hours_per_week": "Weekly hours of physical exercise.",
    "sleep_hours": "Average hours of sleep per night.",
    "family_history_heart_disease": "Indicates whether the patient has a family history of heart disease.",
    "diet_quality_score": "Score (1–10) representing the quality of diet.",
    "alcohol_units_per_week": "Weekly alcohol consumption.",
    "heart_disease_risk_score": "Calculated cardiovascular risk score (0–100).",
    "risk_category": "Risk classification: Low, Medium, or High."
}

data_dictionary['Description'] = data_dictionary['Field Name'].map(descriptions)

data_dictionary

,Field Name,Data Type,Description
0,Patient_ID,int64,Unique identifier for each patient.
1,age,int64,Age of the patient in years.
2,bmi,float64,"Body Mass Index, indicating body fat based on ..."
3,systolic_bp,int64,Systolic blood pressure level.
4,diastolic_bp,int64,Diastolic blood pressure level.
5,cholesterol_mg_dl,int64,Total cholesterol level in mg/dL.
6,resting_heart_rate,int64,Resting heart rate in beats per minute.
7,smoking_status,object,"Smoking category (Never, Former, Current)."
8,daily_steps,int64,Average number of steps taken per day.
9,stress_level,int64,Stress level on a scale from 1 to 10.
10,physical_activity_hours_per_week,float64,Weekly hours of physical exercise.
11,sleep_hours,float64,Average hours of sleep per night.
12,family_history_heart_disease,object,Indicates whether the patient has a family his...
13,diet_quality_score,int64,Score (1–10) representing the quality of diet.
14,alcohol_units_per_week,float64,Weekly alcohol consumption.
15,heart_disease_risk_score,float64,Calculated cardiovascular risk score (0–100).
16,risk_category,object,"Risk classification: Low, Medium, or High."

In [5]:
# Add Length
data_dictionary['Length'] = data_dictionary['Field Name'].apply(lambda x: df[x].shape[0])

# Add Unique Values 
data_dictionary['Unique Values'] = data_dictionary['Field Name'].apply(lambda x: df[x].nunique())

#Add Missing Values
data_dictionary['Missing Values'] = data_dictionary['Field Name'].apply(lambda x: df[x].isnull().sum())

data_dictionary

,Field Name,Data Type,Description,Length,Unique Values,Missing Values
0,Patient_ID,int64,Unique identifier for each patient.,5500,5500,0
1,age,int64,Age of the patient in years.,5500,73,0
2,bmi,float64,"Body Mass Index, indicating body fat based on ...",5500,232,0
3,systolic_bp,int64,Systolic blood pressure level.,5500,82,0
4,diastolic_bp,int64,Diastolic blood pressure level.,5500,55,0
5,cholesterol_mg_dl,int64,Total cholesterol level in mg/dL.,5500,166,0
6,resting_heart_rate,int64,Resting heart rate in beats per minute.,5500,41,0
7,smoking_status,object,"Smoking category (Never, Former, Current).",5500,3,0
8,daily_steps,int64,Average number of steps taken per day.,5500,4211,0
9,stress_level,int64,Stress level on a scale from 1 to 10.,5500,10,0
10,physical_activity_hours_per_week,float64,Weekly hours of physical exercise.,5500,123,0
11,sleep_hours,float64,Average hours of sleep per night.,5500,61,0
12,family_history_heart_disease,object,Indicates whether the patient has a family his...,5500,2,0
13,diet_quality_score,int64,Score (1–10) representing the quality of diet.,5500,10,0
14,alcohol_units_per_week,float64,Weekly alcohol consumption.,5500,196,0
15,heart_disease_risk_score,float64,Calculated cardiovascular risk score (0–100).,5500,921,0
16,risk_category,object,"Risk classification: Low, Medium, or High.",5500,3,0

In [6]:
# Add Minimum and Maximum Values
def min_max_uniform(col):
    try:
        # Try numeric conversion first
        numeric_col = pd.to_numeric(df[col], errors='coerce')
        if numeric_col.notnull().any():
            return pd.Series({'Min.': numeric_col.min(), 'Max.': numeric_col.max()})
        else:
            # If object, use alphabetical min/max
            obj_col = df[col].dropna().astype(str)
            return pd.Series({'Min.': obj_col.min(), 'Max.': obj_col.max()})
    except:
        return pd.Series({'Min.': np.nan, 'Max.': np.nan})

min_max_df = data_dictionary['Field Name'].apply(min_max_uniform)
data_dictionary = pd.concat([data_dictionary, min_max_df], axis=1)

data_dictionary

,Field Name,Data Type,Description,Length,Unique Values,Missing Values,Min.,Max.
0,Patient_ID,int64,Unique identifier for each patient.,5500,5500,0,1,5500
1,age,int64,Age of the patient in years.,5500,73,0,18,90
2,bmi,float64,"Body Mass Index, indicating body fat based on ...",5500,232,0,15.0,40.9
3,systolic_bp,int64,Systolic blood pressure level.,5500,82,0,108,192
4,diastolic_bp,int64,Diastolic blood pressure level.,5500,55,0,64,120
5,cholesterol_mg_dl,int64,Total cholesterol level in mg/dL.,5500,166,0,147,331
6,resting_heart_rate,int64,Resting heart rate in beats per minute.,5500,41,0,48,92
7,smoking_status,object,"Smoking category (Never, Former, Current).",5500,3,0,Current,Never
8,daily_steps,int64,Average number of steps taken per day.,5500,4211,0,500,16793
9,stress_level,int64,Stress level on a scale from 1 to 10.,5500,10,0,1,10
10,physical_activity_hours_per_week,float64,Weekly hours of physical exercise.,5500,123,0,0.0,12.9
11,sleep_hours,float64,Average hours of sleep per night.,5500,61,0,4.0,10.0
12,family_history_heart_disease,object,Indicates whether the patient has a family his...,5500,2,0,No,Yes
13,diet_quality_score,int64,Score (1–10) representing the quality of diet.,5500,10,0,1,10
14,alcohol_units_per_week,float64,Weekly alcohol consumption.,5500,196,0,0.0,29.2
15,heart_disease_risk_score,float64,Calculated cardiovascular risk score (0–100).,5500,921,0,0.0,100.0
16,risk_category,object,"Risk classification: Low, Medium, or High.",5500,3,0,High,Medium

In [11]:
print(data_dictionary.to_string(index=False))

                      Field Name Data Type                                                          Description  Length  Unique Values  Missing Values    Min.   Max.
                      Patient_ID     int64                                  Unique identifier for each patient.    5500           5500               0       1   5500
                             age     int64                                         Age of the patient in years.    5500             73               0      18     90
                             bmi   float64     Body Mass Index, indicating body fat based on height and weight.    5500            232               0    15.0   40.9
                     systolic_bp     int64                                       Systolic blood pressure level.    5500             82               0     108    192
                    diastolic_bp     int64                                      Diastolic blood pressure level.    5500             55               0      64    120
               cholesterol_mg_dl     int64                                    Total cholesterol level in mg/dL.    5500            166               0     147    331
              resting_heart_rate     int64                              Resting heart rate in beats per minute.    5500             41               0      48     92
                  smoking_status    object                           Smoking category (Never, Former, Current).    5500              3               0 Current  Never
                     daily_steps     int64                               Average number of steps taken per day.    5500           4211               0     500  16793
                    stress_level     int64                                Stress level on a scale from 1 to 10.    5500             10               0       1     10
physical_activity_hours_per_week   float64                                   Weekly hours of physical exercise.    5500            123               0     0.0   12.9
                     sleep_hours   float64                                    Average hours of sleep per night.    5500             61               0     4.0   10.0
    family_history_heart_disease    object Indicates whether the patient has a family history of heart disease.    5500              2               0      No    Yes
              diet_quality_score     int64                       Score (1–10) representing the quality of diet.    5500             10               0       1     10
          alcohol_units_per_week   float64                                          Weekly alcohol consumption.    5500            196               0     0.0   29.2
        heart_disease_risk_score   float64                        Calculated cardiovascular risk score (0–100).    5500            921               0     0.0  100.0
                   risk_category    object                           Risk classification: Low, Medium, or High.    5500              3               0    High Medium

In [14]:
print(data_dictionary.to_markdown(index=False))

| Field Name                       | Data Type   | Description                                                          |   Length |   Unique Values |   Missing Values | Min.    | Max.   |
|:---------------------------------|:------------|:---------------------------------------------------------------------|---------:|----------------:|-----------------:|:--------|:-------|
| Patient_ID                       | int64       | Unique identifier for each patient.                                  |     5500 |            5500 |                0 | 1       | 5500   |
| age                              | int64       | Age of the patient in years.                                         |     5500 |              73 |                0 | 18      | 90     |
| bmi                              | float64     | Body Mass Index, indicating body fat based on height and weight.     |     5500 |             232 |                0 | 15.0    | 40.9   |
| systolic_bp                      | int64       | Systolic blood pressure level.                                       |     5500 |              82 |                0 | 108     | 192    |
| diastolic_bp                     | int64       | Diastolic blood pressure level.                                      |     5500 |              55 |                0 | 64      | 120    |
| cholesterol_mg_dl                | int64       | Total cholesterol level in mg/dL.                                    |     5500 |             166 |                0 | 147     | 331    |
| resting_heart_rate               | int64       | Resting heart rate in beats per minute.                              |     5500 |              41 |                0 | 48      | 92     |
| smoking_status                   | object      | Smoking category (Never, Former, Current).                           |     5500 |               3 |                0 | Current | Never  |
| daily_steps                      | int64       | Average number of steps taken per day.                               |     5500 |            4211 |                0 | 500     | 16793  |
| stress_level                     | int64       | Stress level on a scale from 1 to 10.                                |     5500 |              10 |                0 | 1       | 10     |
| physical_activity_hours_per_week | float64     | Weekly hours of physical exercise.                                   |     5500 |             123 |                0 | 0.0     | 12.9   |
| sleep_hours                      | float64     | Average hours of sleep per night.                                    |     5500 |              61 |                0 | 4.0     | 10.0   |
| family_history_heart_disease     | object      | Indicates whether the patient has a family history of heart disease. |     5500 |               2 |                0 | No      | Yes    |
| diet_quality_score               | int64       | Score (1–10) representing the quality of diet.                       |     5500 |              10 |                0 | 1       | 10     |
| alcohol_units_per_week           | float64     | Weekly alcohol consumption.                                          |     5500 |             196 |                0 | 0.0     | 29.2   |
| heart_disease_risk_score         | float64     | Calculated cardiovascular risk score (0–100).                        |     5500 |             921 |                0 | 0.0     | 100.0  |
| risk_category                    | object      | Risk classification: Low, Medium, or High.                           |     5500 |               3 |                0 | High    | Medium |